---
- name: kubernetes and docker installation
  hosts: localhost
  vars:
    - kubernetes_role: master
  tasks:
    - shell:
        cmd: apt-get update -y
    - include_role:
        name: geerlingguy.docker
    - include_role:
        name: geerlingguy.kubernetes
    - package:
        name: 'bash-completion'
        state: present
    - name: configuration
      copy:
        src:   /etc/kubernetes/admin.conf
        dest:  "{{ lookup('env', 'HOME')}}/.kube"
        mode: "0644"

    - name: bash completion
      shell:
        cmd:  kubectl completion bash > /etc/bash_completion.d/kubectl




- name: kubernetes and docker installation
  hosts: all
  vars:
    - kubernetes_role: node
  tasks:
    - shell:
        cmd: apt-get update -y
    - include_role:
        name: geerlingguy.docker
    - include_role:
        name: geerlingguy.kubernetes

