---
- name: kubernetes and docker installation
  hosts: localhost
  vars:
    - kubernetes_role: master
  tasks:
    - shell:
        cmd: apt-get update -y
    - include_role:
        name: geerlingguy.docker
    - include_role:
        name: geerlingguy.kubernetes
    - package:
        name: 'bash-completion'
        state: present
    - name: configuration
      copy:
        src:   /etc/kubernetes/admin.conf
        dest:  {{ lookup('env', 'HOME') }}/.kube
        
    - name: bash completion
      shell:
        cmd: cd /etc/bash_completion.d/ ; kubectl completion bash
        
       
   
  
- name: kubernetes and docker installation
  hosts: all
  vars:
    - kubernetes_role: node
  tasks:
    - shell:
        cmd: apt-get update -y
    - include_role:
        name: geerlingguy.docker
    - include_role:
        name: geerlingguy.kubernetes
        
