---
- name: kubernetes and docker installation
  hosts: localhost
  vars:
    - kubernetes_role: master
  tasks:
    - shell:
        cmd: apt-get update -y
    - include_role:
        name: geerlingguy.docker
    - include_role:
        name: geerlingguy.kubernetes

- name: kubernetes and docker installation
  hosts: all
  vars:
    - kubernetes_role: node
  tasks:
    - shell:
        cmd: apt-get update -y
    - include_role:
        name: geerlingguy.docker
    - include_role:
        name: geerlingguy.kubernetes
